// This file was automatically generated by VS extension Windows Machine Learning Code Generator v3
// from model file HeartFailureClassifier.onnx
// Warning: This file may get overwritten if you add add an onnx file with the same name
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Windows.Media;
using Windows.Storage;
using Windows.Storage.Streams;
using Windows.AI.MachineLearning;
namespace HeartFailure
{
    
    public sealed class HeartFailureClassifierInput
    {
        public ImageFeatureValue modelInput; // shape(-1,3,512,512)
    }
    
    public sealed class HeartFailureClassifierOutput
    {
        public TensorFloat modelOutput; // shape(-1,2)
    }
    
    public sealed class HeartFailureClassifierModel
    {
        private LearningModel model;
        private LearningModelSession session;
        private LearningModelBinding binding;
        public static async Task<HeartFailureClassifierModel> CreateFromStreamAsync(IRandomAccessStreamReference stream)
        {
            HeartFailureClassifierModel learningModel = new HeartFailureClassifierModel();
            learningModel.model = await LearningModel.LoadFromStreamAsync(stream);
            learningModel.session = new LearningModelSession(learningModel.model);
            learningModel.binding = new LearningModelBinding(learningModel.session);
            return learningModel;
        }
        public async Task<HeartFailureClassifierOutput> EvaluateAsync(HeartFailureClassifierInput input)
        {
            binding.Bind("modelInput", input.modelInput);
            var result = await session.EvaluateAsync(binding, "0");
            var output = new HeartFailureClassifierOutput();
            output.modelOutput = result.Outputs["modelOutput"] as TensorFloat;
            return output;
        }
    }
}

